CREATE TABLE IF NOT EXISTS links (
	ind INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	steamid64 BIGINT UNSIGNED,
	panel_url VARCHAR(255),
	client_ip VARCHAR(65),
	sent_ip VARCHAR(65),
	sent_port INT UNSIGNED,
	real_ip VARCHAR(65),
	panel_title VARCHAR(64),
	panel_hidden TINYINT(1),
	panel_width INT UNSIGNED,
	panel_height INT UNSIGNED,
	created_at BIGINT UNSIGNED
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8;

CREATE TABLE IF NOT EXISTS servers (
	ind INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	server_name VARCHAR(64),
	sent_ip VARCHAR(65),
	sent_port INT UNSIGNED,
	real_ip VARCHAR(65),
	server_token VARCHAR(65),
	is_blocked TINYINT(1),
	created_at BIGINT UNSIGNED,
	hits INT UNSIGNED NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8;
